export function cleanInput(input) {
  const wordSpaceDigits = input.trim().toLowerCase().replace(/[^\w\s\d]/gi, "");
  const cleanedContractions = removeContractions(wordSpaceDigits);
  return removeUselessWords(cleanedContractions);
}

function removeContractions(input) {
    return input.replace(/aight/g, "alright")
    .replace(/ aint /g, "is not")
    .replace(/amnt/g, "am not")
    .replace(/ arent /g, "are not")
    .replace(/ cant /g, "cannot")
    .replace(/ cause /g, "because")
    .replace(/couldve/g, "could have")
    .replace(/couldnt/g, "could not")
    .replace(/couldntve/g, "could not have")
    .replace(/darent/g, "dare not")
    .replace(/daresnt/g, "dare not")
    .replace(/dasnt/g, "dare not")
    .replace(/didnt/g, "did not")
    .replace(/doesnt/g, "does not")
    .replace(/dont/g, "do not")
    .replace(/dunno/g, "do not know")
    .replace(/ dye /g, "do you")
    .replace(/everybodys/g, "")
    .replace(/everyones/g, "")
    .replace(/finna/g, "going to")
    .replace(/gday/g, "good day")
    .replace(/gimme/g, "give me")
    .replace(/givn/g, "given")
    .replace(/gonna/g, "going to")
    .replace(/gont/g, "go not")
    .replace(/gotta/g, "got to")
    .replace(/hadnt/g, "had not")
    .replace(/hadve/g, "had have")
    .replace(/hasnt/g, "has not")
    .replace(/havent/g, "have not")
    .replace(/ hed /g, "")
    .replace(/ hes /g, "")
    .replace(/heve/g, "")
    .replace(/ howd /g, "how did")
    .replace(/howll/g, "how will")
    .replace(/howre/g, "how are")
    .replace(/ hows /g, "how is")
    .replace(/innit/g, "is it not")
    .replace(/isnt/g, "is not")
    .replace(/itd/g, "it would")
    .replace(/itll/g, "it will")
    .replace(/iunno/g, "I do not know")
    .replace(/lets/g, "let us")
    .replace(/maam/g, "")
    .replace(/maynt/g, "may not")
    .replace(/mayve/g, "may have")
    .replace(/methinks/g, "")
    .replace(/mightnt/g, "might not")
    .replace(/mightve/g, "might have")
    .replace(/mustnt/g, "must not")
    .replace(/mustntve/g, "must not have")
    .replace(/mustve/g, "must have")
    .replace(/neednt/g, "need not")
    .replace(/neer/g, "never")
    .replace(/oclock/g, "of the clock")
    .replace(/ ol /g, "old")
    .replace(/oughtnt/g, "ought not")
    .replace(/shallnt/g, "shall not")
    .replace(/shant/g, "shall not")
    .replace(/shes/g, "she has")
    .replace(/shouldve/g, "should have")
    .replace(/shouldnt/g, "should not")
    .replace(/shouldntve/g, "should not have")
    .replace(/somebodys/g, "")
    .replace(/someones/g, "")
    .replace(/thatll/g, "that will")
    .replace(/thatre/g, "that are")
    .replace(/thats/g, "that is")
    .replace(/thatd/g, "that would")
    .replace(/thered/g, "there would")
    .replace(/therell/g, "there will")
    .replace(/therere/g, "there are")
    .replace(/theres/g, "there is")
    .replace(/thesere/g, "these are")
    .replace(/theseve/g, "these have")
    .replace(/theyd/g, "")
    .replace(/theyll/g, "")
    .replace(/theyre/g, "")
    .replace(/theyve/g, "")
    .replace(/thosere/g, "")
    .replace(/thoseve/g, "")
    .replace(/ tis /g, "")
    .replace(/ tove /g, "to have")
    .replace(/ twas /g, "it was")
    .replace(/wanna/g, "want to")
    .replace(/wasnt/g, "was not")
    .replace(/wedve/g, "we would have")
    .replace(/were/g, "")
    .replace(/weve/g, "")
    .replace(/werent/g, "were not")
    .replace(/whatd/g, "what did")
    .replace(/whatll/g, "what will")
    .replace(/whatre/g, "what are")
    .replace(/whats/g, "what is")
    .replace(/whatve/g, "what have")
    .replace(/whens/g, "when is")
    .replace(/whered/g, "where did")
    .replace(/wherell/g, "where will")
    .replace(/wherere/g, "where are")
    .replace(/wheres/g, "where is")
    .replace(/whereve/g, "where have")
    .replace(/whichd/g, "which would")
    .replace(/whichll/g, "which will")
    .replace(/whichre/g, "which are")
    .replace(/whichs/g, "which is")
    .replace(/whichve/g, "which have")
    .replace(/whod/g, "")
    .replace(/whodve/g, "")
    .replace(/wholl/g, "")
    .replace(/whore/g, "")
    .replace(/whos/g, "")
    .replace(/whove/g, "")
    .replace(/whyd/g, "why did")
    .replace(/whyre/g, "why are")
    .replace(/whys/g, "why is")
    .replace(/willnt/g, "will not")
    .replace(/wont/g, "will not")
    .replace(/wonnot/g, "will not")
    .replace(/wouldve/g, "would have")
    .replace(/wouldnt/g, "would not")
    .replace(/wouldntve/g, "would not have")
    .replace(/yall/g, "")
    .replace(/yalldve/g, "")
    .replace(/yallre/g, "")
    .replace(/youd/g, "")
    .replace(/youll/g, "")
    .replace(/youre/g, "")
    .replace(/youve/g, "");
}

function removeUselessWords(input) {
  return input
    .replace(/ a /g, " ")
    .replace(/ an /g, " ")
    .replace(/ the /g, " ")
    .replace(/ or /g, " ")
    .replace(/ i /g, " ")
    .replace(/ is /g, " ")
    .replace(/ me /g, " ")
    .replace(/ and /g, " ")
    .replace(/ at /g, " ")
    .replace(/ am /g, " ")
    .replace(/ to /g, " ")
    .replace(/ do /g, " ")
    .replace(/ my /g, " ")
    .replace(/ you /g, " ")
    .replace(/ they /g, " ")
    .replace(/ he /g, " ")
    .replace(/ it /g, " ")
    .replace(/ she /g, " ")
    .replace(/ so /g, " ")
    .replace(/ for /g, " ")
    .replace(/ got /g, " ")
    .replace(/ of /g, " ")
    .replace(/ please /g, " ")
    .replace(/ if /g, " ")
    .replace(/ mr /g, " ")
    .replace(/ as /g, " ")
    .replace(/ on /g, " ")
    .replace(/ in /g, " ")
    .replace(/ his /g, " ")
    .replace(/ if /g, " ")
    .replace(/ its /g, " ")
    .replace(/ had /g, " ")
    .replace(/ us /g, " ")
    .replace(/ her /g, " ")
    .replace(/ but /g, " ")
    .replace(/ from /g, " ")
    .replace(/ who /g, " ")
    .replace(/ can /g, " ")
    .replace(/ will /g, " ")
    .replace(/ this /g, " ")
    .replace(/ see /g, " ")
    .replace(/ how /g, " ")
    .replace(/ very /g, " ")
    .replace(/ with /g, " ")
    .replace(/ by /g, " ")
    .replace(/ that /g, " ")
    .replace(/ did /g, " ")
    .replace(/ not /g, " ")
    .replace(/ then /g, " ")
    .replace(/ could /g, " ")
    .replace(/ them /g, " ")
    .replace(/ be /g, " ")
    .replace(/ im /g, " ")
}