/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function SpotLightModel({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF(process.env.PUBLIC_URL + "/Demos/Nut/spotlight.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-0.23, 0, 1.62]} rotation={[Math.PI / 2, 0, 0]} scale={1.5}>
        <mesh geometry={nodes.Circle018_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Circle018_2.geometry} material={materials['Material.002']} />
      </group>
      <mesh geometry={nodes.Circle019.geometry} material={materials['Material.001']} position={[-0.23, 0, 1.62]} rotation={[Math.PI / 2, 0, 0]} scale={1.5} />
      <mesh geometry={nodes.Circle020.geometry} material={materials['Material.001']} position={[-0.23, 0, 1.62]} rotation={[Math.PI / 2, 0, 0]} scale={1.5} />
      <mesh geometry={nodes.Circle021.geometry} material={materials['Material.003']} position={[-0.23, 0, 1.62]} rotation={[Math.PI / 2, 0, 0]} scale={1.5} />
      <mesh geometry={nodes.Cube006.geometry} material={materials['Material.001']} position={[-0.23, 0, 1.62]} rotation={[Math.PI / 2, 0, 0]} scale={1.5} />
      <mesh geometry={nodes.Circle024.geometry} material={materials['Material.003']} position={[-0.23, 0, 1.62]} rotation={[Math.PI / 2, 0, 0]} scale={1.5} />
      <mesh geometry={nodes.Circle025.geometry} material={materials['Material.006']} position={[-0.23, 0, 1.62]} rotation={[Math.PI / 2, 0, 0]} scale={1.5} />
      <mesh geometry={nodes.Circle026.geometry} material={materials['Material.003']} position={[-0.23, 0, 1.62]} rotation={[Math.PI / 2, 0, 0]} scale={1.5} />
      <mesh geometry={nodes.Cube007_Cube009.geometry} material={materials['Material.001']} position={[-0.23, 0, 1.62]} rotation={[Math.PI / 2, 0, 0]} scale={1.5} />
      <mesh geometry={nodes.Circle022.geometry} material={materials['Material.001']} position={[-0.23, 0, 1.62]} rotation={[Math.PI / 2, 0, 0]} scale={1.5} />
    </group>
  )
}

useGLTF.preload('/spotlight.gltf');